using System;

public enum ClientPackets
{
    welcomeReceived = 1,
    joinLobby,
    playerPosition,
    playerRotation,
    sendDisconnect,
    sendPing,
    playerKilled,
    ready,
    requestSpawns,
    dropItem,
    dropItemAtPosition,
    pickupItem,
    weaponInHand,
    playerHitObject,
    animationUpdate,
    requestBuild,
    requestChest,
    updateChest,
    pickupInteract,
    playerHit,
    playerDamageMob,
    shrineCombatStart,
    sendChatMessage,
    playerPing,
    sendArmor,
    playerHp,
    playerDied,
    shootArrow,
    finishedLoading,
    spawnEffect,
    reviveRequest,
	interact,
	startedLoading,
	shipUpdate,

    _vehicleOffset = 2360,
    moveVehicle,
    enterVehicle,
    exitVehicle,
}
